name: CI (OSS)

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read

jobs:
  test:
    uses: ./.github/workflows/test.yml
    with:
      saas: false
